#include <bits/stdc++.h>
#define oof using
#define oofoof namespace
#define oofoofoof std
#define oofoofoofoof ;
#define oofoofoofoofoof int
#define oofoofoofoofoofoof main
#define oofoofoofoofoofoofoof {
#define oofoofoofoofoofoofoofoof ios
#define oofoofoofoofoofoofoofoofoof sync_with_stdio
#define oofoofoofoofoofoofoofoofoofoof false
#define oofoofoofoofoofoofoofoofoofoofoof cin.tie
#define oofoofoofoofoofoofoofoofoofoofoofoof NULL
#define oofoofoofoofoofoofoofoofoofoofoofoofoof t
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoof 1
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoof cin
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof while
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof n
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof if
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof 2
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof cout
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof '7'
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof for
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof i
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof 0
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof '1'
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof }
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof else
#define oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof '\n'
oof oofoof oofoofoof oofoofoofoof

oofoofoofoofoof oofoofoofoofoofoof() oofoofoofoofoofoofoof
oofoofoofoofoofoofoofoof::oofoofoofoofoofoofoofoofoof(oofoofoofoofoofoofoofoofoofoof) oofoofoofoof oofoofoofoofoofoofoofoofoofoofoof(oofoofoofoofoofoofoofoofoofoofoofoof) oofoofoofoof

oofoofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoof = oofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoof >> oofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof

oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof(oofoofoofoofoofoofoofoofoofoofoofoofoof--) oofoofoofoofoofoofoof
oofoofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoofoofoof >> oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof

oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof(oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof % oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof) oofoofoofoofoofoofoof
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof << oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof

oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof(oofoofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof = oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof < oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof / oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof - oofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof++)
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof << oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof

oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof  oofoofoofoofoofoofoof
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof(oofoofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof = oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof < oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof / oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof++)
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof << oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof

oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof << oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof oofoofoofoof
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof
oofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoof